#pragma once
#define INFRANTRIES "in"
#define MECHS "me"
#define ROCKETS "ro"
#define RECONS "re"
#define APCS "ap"
#define ANTI_AIRS "aa"
#define ARTILLERY "ar"
#define TANKS "ta"
#define MED_TANKS "mt"
